
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
import json
# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def load_extended_sql_data(filename):
    with open(filename, 'r') as file:
        data = json.load(file)
        return data


def query():
    load_dotenv()

    user = os.getenv('USER')
    password = '' #load from file
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect(host = 'localhost', dbname = 'postgres', user= "postgres", password="0812", port = 5432, cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    for row in cur:
        if row['quant'] > 10:
            _global.append(row)
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    # Assuming the filename is 'data.json'
    data = load_extended_sql_data('data.json')
    print("Projected Attributes (S):", data['S'])
    print("Number of Grouping Variables (n):", data['n'])
    print("Group By Attributes (V):", data['V'])
    print("Aggregate Functions (F vector):", data['F_vector'])
    print("Predicate Vector:", data['theta_vector'])
    print("Having Conditions:", data['having'])
    print(query())
    
if "__main__" == __name__:
    main()
    